engines/blife/config/routes.rb
Blife::Engine.routes.draw do
  resources :severities
  resources :priorities
  resources :defects
  root 'defects#index'
end

engines/blife/app/models/blife/application_record.rb
module Blife
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/blife/app/models/blife/defect.rb
module Blife
  class Defect < ApplicationRecord
    has_one :severity
    has_one :priority
    
  end
end

engines/blife/app/models/blife/priority.rb
module Blife
  class Priority < ApplicationRecord
    
  end
end

engines/blife/app/models/blife/severity.rb
module Blife
  class Severity < ApplicationRecord

 
  end
end

engines/blife/app/controllers/blife/application_controller.rb
module Blife
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    layout 'layouts/application'
  end
end

engines/blife/app/controllers/blife/defects_controller.rb
require_dependency "blife/application_controller"

module Blife
  class DefectsController < ApplicationController
    before_action :set_defect, only: [:show, :edit, :update, :destroy]
  
    # GET /defects
    def index
      @defects = Defect.all
    end

    # GET /defects/1
    def show
    end

    # GET /defects/new
    def new
      @defect = Defect.new()
    end

    # GET /defects/1/edit
    def edit
    end

    # POST /defects
    def create
      require 'pry'
     binding.pry
      @defect = Defect.new(defect_params)
     
      if @defect.save
      
        redirect_to @defect, notice: 'Defect was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /defects/1
    def update
      if @defect.update(defect_params)
        redirect_to @defect, notice: 'Defect was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /defects/1
    def destroy
      @defect.destroy
      redirect_to defects_url, notice: 'Defect was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_defect
        @defect = Defect.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def defect_params
        params.require(:defect).permit(:summary, :description, :expected, :actual, :steps_to_reproduce, :blife_severity_id, :blife_priority_id)
      end
      
      def priority_options
        Priority.all.map{|p| [p.id,p.name]}
      end
      
      def severity_options
        Severity.all.map{|s| [s.id,s.name]}
      end
  end
end

engines/blife/app/controllers/blife/priorities_controller.rb
require_dependency "blife/application_controller"

module Blife
  class PrioritiesController < ApplicationController
    before_action :set_priority, only: [:show, :edit, :update, :destroy]

    # GET /priorities
    def index
      @priorities = Priority.all
    end

    # GET /priorities/1
    def show
    end

    # GET /priorities/new
    def new
      @priority = Priority.new
    end

    # GET /priorities/1/edit
    def edit
    end

    # POST /priorities
    def create
      @priority = Priority.new(priority_params)

      if @priority.save
        redirect_to @priority, notice: 'Priority was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /priorities/1
    def update
      if @priority.update(priority_params)
        redirect_to @priority, notice: 'Priority was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /priorities/1
    def destroy
      @priority.destroy
      redirect_to priorities_url, notice: 'Priority was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_priority
        @priority = Priority.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def priority_params
        params.require(:priority).permit(:name, :description)
      end
  end
end

engines/blife/app/controllers/blife/severities_controller.rb
require_dependency "blife/application_controller"

module Blife
  class SeveritiesController < ApplicationController
    before_action :set_severity, only: [:show, :edit, :update, :destroy]

    # GET /severities
    def index
      @severities = Severity.all
    end

    # GET /severities/1
    def show
    end

    # GET /severities/new
    def new
      @severity = Severity.new
    end

    # GET /severities/1/edit
    def edit
    end

    # POST /severities
    def create
      @severity = Severity.new(severity_params)

      if @severity.save
        redirect_to @severity, notice: 'Severity was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /severities/1
    def update
      if @severity.update(severity_params)
        redirect_to @severity, notice: 'Severity was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /severities/1
    def destroy
      @severity.destroy
      redirect_to severities_url, notice: 'Severity was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_severity
        @severity = Severity.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def severity_params
        params.require(:severity).permit(:name, :description)
      end
  end
end

engines/blife/app/helpers/blife/application_helper.rb
module Blife
  module ApplicationHelper
  end
end

engines/blife/app/helpers/blife/defects_helper.rb
module Blife
  module DefectsHelper
  end
end

engines/blife/app/helpers/blife/priorities_helper.rb
module Blife
  module PrioritiesHelper
  end
end

engines/blife/app/helpers/blife/severities_helper.rb
module Blife
  module SeveritiesHelper
  end
end

engines/blife/app/views/blife/defects/_form.html.erb
<%= form_for(defect) do |f| %>
  <% if defect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(defect.errors.count, "error") %> prohibited this defect from being saved:</h2>

      <ul>
      <% defect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :summary %>
    <%= f.text_field :summary %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :expected %>
    <%= f.text_area :expected %>
  </div>

  <div class="field">
    <%= f.label :actual %>
    <%= f.text_area :actual %>
  </div>

  <div class="field">
    <%= f.label :steps_to_reproduce %>
    <%= f.text_area :steps_to_reproduce %>
  </div>

  <div class="field">
    <%= f.label :severity %>
    <%= f.collection_select(:blife_severity_id,Blife::Severity.all,:id,:name) %>
   
  </div>

  <div class="field">
    <%= f.label :priority %>
    <%= f.collection_select(:blife_priority_id,Blife::Priority.all,:id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

engines/blife/app/views/blife/defects/edit.html.erb
<h1>Editing Defect</h1>

<%= render 'form', defect: @defect %>

<%= link_to 'Show', @defect %> |
<%= link_to 'Back', defects_path %>

engines/blife/app/views/blife/defects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Defects</h1>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Summary</th>
      <th>Description</th>
      <th>Expected</th>
      <th>Actual</th>
      <th>Steps to reproduce</th>
      <th>Severity</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @defects.each do |defect| %>
      <tr>
        <td><%= defect.summary %></td>
        <td><%= defect.description %></td>
        <td><%= defect.expected %></td>
        <td><%= defect.actual %></td>
        <td><%= defect.steps_to_reproduce %></td>
        <td><%= defect.blife_severity_id %></td>
        <td><%= defect.blife_priority_id %></td>
        <td><%= link_to 'Show', defect %></td>
        <td><%= link_to 'Edit', edit_defect_path(defect) %></td>
        <td><%= link_to 'Destroy', defect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

<%= link_to 'New Defect', new_defect_path %>

engines/blife/app/views/blife/defects/new.html.erb
<h1>New Defect</h1>

<%= render 'form', defect: @defect %>

<%= link_to 'Back', defects_path %>

engines/blife/app/views/blife/defects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Summary:</strong>
  <%= @defect.summary %>
</p>

<p>
  <strong>Description:</strong>
  <%= @defect.description %>
</p>

<p>
  <strong>Expected:</strong>
  <%= @defect.expected %>
</p>

<p>
  <strong>Actual:</strong>
  <%= @defect.actual %>
</p>

<p>
  <strong>Steps to reproduce:</strong>
  <%= @defect.steps_to_reproduce %>
</p>

<p>
  <strong>Severity:</strong>
  <%= @defect.blife_severity_id %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @defect.blife_priority_id%>
</p>

<%= link_to 'Edit', edit_defect_path(@defect) %> |
<%= link_to 'Back', defects_path %>

engines/blife/app/views/blife/priorities/_form.html.erb
<div class="defectform">
<%= form_for(priority) do |f| %>
  <% if priority.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(priority.errors.count, "error") %> prohibited this priority from being saved:</h2>

      <ul>
      <% priority.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

engines/blife/app/views/blife/priorities/edit.html.erb
<h1>Editing Priority</h1>

<%= render 'form', priority: @priority %>

<%= link_to 'Show', @priority %> |
<%= link_to 'Back', priorities_path %>

engines/blife/app/views/blife/priorities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Priorities</h1>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @priorities.each do |priority| %>
      <tr>
        <td><%= priority.name %></td>
        <td><%= priority.description %></td>
        <td><%= link_to 'Show', priority %></td>
        <td><%= link_to 'Edit', edit_priority_path(priority) %></td>
        <td><%= link_to 'Destroy', priority, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

<%= link_to 'New Priority', new_priority_path %>

engines/blife/app/views/blife/priorities/new.html.erb
<h1>New Priority</h1>

<%= render 'form', priority: @priority %>

<%= link_to 'Back', priorities_path %>

engines/blife/app/views/blife/priorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @priority.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @priority.description %>
</p>

<%= link_to 'Edit', edit_priority_path(@priority) %> |
<%= link_to 'Back', priorities_path %>

engines/blife/app/views/blife/severities/_form.html.erb
<%= form_for(severity) do |f| %>
  <% if severity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(severity.errors.count, "error") %> prohibited this severity from being saved:</h2>

      <ul>
      <% severity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

engines/blife/app/views/blife/severities/edit.html.erb
<h1>Editing Severity</h1>

<%= render 'form', severity: @severity %>

<%= link_to 'Show', @severity %> |
<%= link_to 'Back', severities_path %>

engines/blife/app/views/blife/severities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Severities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @severities.each do |severity| %>
      <tr>
        <td><%= severity.name %></td>
        <td><%= severity.description %></td>
        <td><%= link_to 'Show', severity %></td>
        <td><%= link_to 'Edit', edit_severity_path(severity) %></td>
        <td><%= link_to 'Destroy', severity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Severity', new_severity_path %>

engines/blife/app/views/blife/severities/new.html.erb
<h1>New Severity</h1>

<%= render 'form', severity: @severity %>

<%= link_to 'Back', severities_path %>

engines/blife/app/views/blife/severities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @severity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @severity.description %>
</p>

<%= link_to 'Edit', edit_severity_path(@severity) %> |
<%= link_to 'Back', severities_path %>

engines/blife/app/views/layouts/blife/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blife</title>
  <%= stylesheet_link_tag    "blife/application", media: "all" %>
  <%= javascript_include_tag "blife/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>