engines/wpractice/config/routes.rb
Wpractice::Engine.routes.draw do
  resources :products
  resources :practices
end

engines/wpractice/app/models/wpractice/application_record.rb
module Wpractice
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/wpractice/app/models/wpractice/practice.rb
module Wpractice
  class Practice < ApplicationRecord
  end
end

engines/wpractice/app/models/wpractice/product.rb
module Wpractice
  class Product < ApplicationRecord
  end
end

engines/wpractice/app/controllers/wpractice/application_controller.rb
module Wpractice
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    layout 'layouts/application'
  end
end

engines/wpractice/app/controllers/wpractice/practices_controller.rb
require_dependency "wpractice/application_controller"

module Wpractice
  class PracticesController < ApplicationController
    before_action :set_practice, only: [:show, :edit, :update, :destroy]

    # GET /practices
    def index
      @practices = Practice.all
    end

    # GET /practices/1
    def show
    end

    # GET /practices/new
    def new
      @practice = Practice.new
    end

    # GET /practices/1/edit
    def edit
    end

    # POST /practices
    def create
      @practice = Practice.new(practice_params)

      if @practice.save
        redirect_to @practice, notice: 'Practice was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /practices/1
    def update
      if @practice.update(practice_params)
        redirect_to @practice, notice: 'Practice was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /practices/1
    def destroy
      @practice.destroy
      redirect_to practices_url, notice: 'Practice was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_practice
        @practice = Practice.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def practice_params
        params.require(:practice).permit(:name, :description)
      end
  end
end

engines/wpractice/app/controllers/wpractice/products_controller.rb
require_dependency "wpractice/application_controller"

module Wpractice
  class ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    # GET /products
    def index
      @products = Product.all
    end

    # GET /products/1
    def show
    end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products
    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /products/1
    def update
      if @product.update(product_params)
        redirect_to @product, notice: 'Product was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /products/1
    def destroy
      @product.destroy
      redirect_to products_url, notice: 'Product was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def product_params
        params.require(:product).permit(:name, :description)
      end
  end
end

engines/wpractice/app/helpers/wpractice/application_helper.rb
module Wpractice
  module ApplicationHelper
  end
end

engines/wpractice/app/helpers/wpractice/practices_helper.rb
module Wpractice
  module PracticesHelper
  end
end

engines/wpractice/app/helpers/wpractice/products_helper.rb
module Wpractice
  module ProductsHelper
  end
end

engines/wpractice/app/views/layouts/wpractice/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wpractice</title>
  <%= stylesheet_link_tag    "wpractice/application", media: "all" %>
  <%= javascript_include_tag "wpractice/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

engines/wpractice/app/views/wpractice/practices/_form.html.erb
<%= form_for(practice) do |f| %>
  <% if practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

engines/wpractice/app/views/wpractice/practices/edit.html.erb
<h1>Editing Practice</h1>

<%= render 'form', practice: @practice %>

<%= link_to 'Show', @practice %> |
<%= link_to 'Back', practices_path %>

engines/wpractice/app/views/wpractice/practices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Practices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= practice.name %></td>
        <td><%= practice.description %></td>
        <td><%= link_to 'Show', practice %></td>
        <td><%= link_to 'Edit', edit_practice_path(practice) %></td>
        <td><%= link_to 'Destroy', practice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Practice', new_practice_path %>

engines/wpractice/app/views/wpractice/practices/new.html.erb
<h1>New Practice</h1>

<%= render 'form', practice: @practice %>

<%= link_to 'Back', practices_path %>

engines/wpractice/app/views/wpractice/practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @practice.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @practice.description %>
</p>

<%= link_to 'Edit', edit_practice_path(@practice) %> |
<%= link_to 'Back', practices_path %>

engines/wpractice/app/views/wpractice/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

engines/wpractice/app/views/wpractice/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

engines/wpractice/app/views/wpractice/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

engines/wpractice/app/views/wpractice/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

engines/wpractice/app/views/wpractice/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>